name: novel_analyzer
description: "网文拆解器 - Flutter版"
publish_to: 'none'
version: 1.0.734+734

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  open_filex: ^4.5.0
  audioplayers: ^6.1.0
  flutter_tts: ^4.0.2
  scrollable_positioned_list: ^0.3.8
  share_plus: ^13.3.0
  file_selector: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
